##NumPy

###Get the data

In [1]:
names = ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
call_numbers = [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
average_deal_size = [8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
revenues = [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]

In [2]:
import numpy as np

#Create an empty array with the data type integer
data = np.array([], dtype=int)

###Functions

In [3]:
def append_names(names_list):
  global data
  for i in names_list:
    data = np.append(data, names.index(i))

In [4]:
def append_performance_measures(feature_list):
  global data
  data = np.append(data, feature_list)

In [5]:
append_names(names)
append_performance_measures(call_numbers)
append_performance_measures(average_deal_size)
append_performance_measures(revenues)


print(data)
print(data.shape)

[    0     1     2     3     4     5     6     7     8     9    10   300
    10   500    70   100   100   600   800   200   450    80     8     6
    24    32     5    25    25    40    15    10    12  2400    60 12000
  2275   500   770  4000  6000   800  1200   500]
(44,)


###Reshape the array

In [6]:
#Change the array structure to 4 rows and 11 columns
data = data.reshape(4, 11)

print(data)
print(data.shape)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]]
(4, 11)


In [7]:
#Print the name indexes
print(data[0])

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
#Print the number of calls
print(data[1])

[300  10 500  70 100 100 600 800 200 450  80]


In [9]:
#Print the average deal sizes
print(data[2])

[ 8  6 24 32  5 25 25 40 15 10 12]


In [10]:
#Print the revenues 
print(data[3])

[ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]


In [11]:
#Print the revenue generated by Ellen
print(data[3, 7])

6000


###Analyzing the data
The performance score of an employee:
\begin{align}
        \text{Performance} = \frac{\text{Average deal size x Revenue}}{\text{Number of calls}}
    \end{align}


In [12]:
def calculate_performance(employee_name):
  idx = names.index(employee_name)
  number_of_calls = data[1, idx]
  avg_deal_size = data[2, idx]
  revenue = data[3, idx]

  score = (avg_deal_size*revenue)/number_of_calls

  return score

In [13]:
#Ellen's performance
print(calculate_performance("Ellen"))

300.0


###Calculate the performance of each employee

In [14]:
performance_scores = []
for name in names:
  score = int(calculate_performance(name))
  performance_scores.append(score)

###Add the scores to the "data" array

In [15]:
data = np.concatenate((data, [performance_scores]), axis=0)

print(data)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]
 [   64    36   576  1040    25   192   166   300    60    26    75]]


###Find out the best and worst performing employees

In [16]:
idx_best_employee = np.argmax(data[4])
idx_worst_employee = np.argmin(data[4])

print(f'Best performaning employee: {names[idx_best_employee]}')
print(f'Worst performaning employee: {names[idx_worst_employee]}')

Best performaning employee: Celine
Worst performaning employee: Sue
